language: node_js

node_js:
  - "6"

cache: yarn
install:
  - yarn install
  - cd client && yarn install && cd -

script: npm run coverage

after_success: 'npm run coveralls'

notifications:
  email: false
